#!/usr/bin/env python3
"""Word accounting for report_main.tex with blue cut-marking.

Counts three ways with the SAME engine (texcount):
  total : the document as it stands (blue included)
  kept  : with every \\cutw{...} span and cutblock environment stripped
  cut   : total - kept

Then applies the official counting rule (FinalReportGuidance): counted = text + headers + captions,
MINUS the layperson's summary (which texcount includes in its totals here).

Run:  python3 count_words.py
"""
import re
import subprocess
import sys
import tempfile
from pathlib import Path

TEX = Path(__file__).with_name("report_main.tex")
TEXCOUNT = "/Library/TeX/texbin/texcount"


def strip_cut(src: str) -> str:
    # remove cutblock environments (non-greedy, DOTALL)
    src = re.sub(r"\\begin\{cutblock\}.*?\\end\{cutblock\}", "", src, flags=re.S)
    # remove \cutw{...} with balanced-brace matching
    out, i = [], 0
    while True:
        j = src.find(r"\cutw{", i)
        if j < 0:
            out.append(src[i:])
            break
        out.append(src[i:j])
        depth, k = 1, j + len(r"\cutw{")
        while k < len(src) and depth:
            if src[k] == "{" and src[k - 1] != "\\":
                depth += 1
            elif src[k] == "}" and src[k - 1] != "\\":
                depth -= 1
            k += 1
        i = k
    return "".join(out)


def texcount(path: Path) -> dict:
    res = subprocess.run([TEXCOUNT, "-sum", "-q", str(path)],
                         capture_output=True, text=True, check=True)
    nums = {}
    for line in res.stdout.splitlines():
        if m := re.match(r"Words in text: (\d+)", line):
            nums["text"] = int(m.group(1))
        elif m := re.match(r"Words in headers: (\d+)", line):
            nums["headers"] = int(m.group(1))
        elif m := re.match(r"Words outside text \(captions, etc\.\): (\d+)", line):
            nums["captions"] = int(m.group(1))
        elif m := re.match(r"\s+(\d+)\+(\d+)\+(\d+) \(.*Section: Layperson", line):
            nums["layperson"] = int(m.group(1)) + int(m.group(2)) + int(m.group(3))
    return nums


def official(n: dict) -> int:
    return n["text"] + n["headers"] + n["captions"] - n.get("layperson", 0)


def main():
    import sys
    write = "--write" in sys.argv
    src = TEX.read_text()
    total = texcount(TEX)
    with tempfile.NamedTemporaryFile("w", suffix=".tex", delete=False) as f:
        f.write(strip_cut(src))
        stripped_path = Path(f.name)
    kept = texcount(stripped_path)
    stripped_path.unlink()

    tot, kep = official(total), official(kept)
    print(f"OFFICIAL COUNT (text+headers+captions, minus layperson; hard max 10,000)")
    print(f"  total (incl. blue): {tot:6d}")
    print(f"  kept  (blue gone) : {kep:6d}")
    print(f"  blue (marked cut) : {tot - kep:6d}")
    print(f"  still to trim     : {max(0, kep - 10000):6d}  (vs hard max)")
    print(f"  [raw texcount total: text={total['text']} headers={total['headers']} "
          f"captions={total['captions']} layperson={total.get('layperson', 0)}]")
    if write:
        # the title page reports the count the submitted document will have, i.e. with the
        # blue cut-marked text removed
        (TEX.parent / "wordcount.tex").write_text(
            "%% generated by count_words.py --write; do not edit\n"
            f"\\newcommand{{\\reportwordcount}}{{{kep:,}}}\n")
        print(f"  wrote wordcount.tex (\\reportwordcount = {kep:,})")


if __name__ == "__main__":
    main()
